// The world: maps, buildings, items lying around, NPCs, and doors between maps.
// Each map row is text, 1 character = 1 tile (16x16 px). `legend` turns characters into tile
// names (all tile names are listed in assets/tiles.json). All positions are in tiles.

const START_MAP = 'campus';

// Multi-tile buildings, stamped onto a map at a position (rows of tile names).
const STRUCTURES = {
  house: [
    ['roofTL', 'roofT', 'roofT', 'roofT', 'roofTR'],
    ['eaveL', 'eave', 'eave', 'eave', 'eaveR'],
    ['wallL', 'houseWindow', 'wall', 'houseWindow', 'wallR'],
    ['wallL', 'wall', 'door', 'wall', 'wallR'],
  ],
};

const MAPS = {
  // The real campus, generated by tools/campus/build-campus.js into assets/maps/campus.json (ADR 0007).
  // Its tiles, spawn point, doors and named areas all come from that file.
  campus: {
    name: 'BITS Dubai Campus',
    tiled: 'campus',
    // docs/STORY.md "Rules for the world": only the story's own route stays open outdoors and into
    // the Main Block; the Library and Mechanical Blocks aren't part of this hunt at all, so they're
    // permanently blocked rather than gated behind a stage (no `stages` list -- see
    // src/maplogic.js isDoorLocked()). The Main Block's own entrance is never in this list: that one
    // stays open from the very start, it's the story's hub.
    doorLocks: [
      { match: 'Library Block entrance' },
      { match: 'Mechanical Block entrance' },
    ],
  },

  // Building interiors (P3), generated by tools/interiors/build-interiors.js into
  // assets/maps/<key>.json (docs/INTERIORS_PLAN.md). 1 m per tile; `indoors: true` turns off
  // running (FB-0017) the same way it does for the house below. Reached from the campus through
  // the `door` objects on campus.json (`to`/`toId`/`facing` -- see world.js `resolveWarpTarget`),
  // and between floors through `stairs` objects the same way.
  //
  // The LUG treasure hunt (docs/STORY.md, M3): the volunteer's stall and the 3 key stations are
  // plain JS data on these map defs (`npcs`/`keyStations`), exactly like the meadow/house test
  // maps' own `npcs` below -- createNpcs()/createKeyStations() (src/scenes/world.js) read `this.def.
  // npcs`/`this.def.keyStations` regardless of whether the map itself is a hand-written text grid or
  // a generated Tiled map, so none of this needed touching tools/interiors/plans.js or regenerating
  // any .json (only the *room* renames in plans.js did, see docs/INTERIORS_PLAN.md).
  'main-block-g': {
    name: 'Main Block · Ground Floor',
    tiled: 'main-block-g',
    indoors: true,
    // Up to the 1st floor only opens once the volunteer has actually given the quest (docs/STORY.md
    // "Rules for the world": "the key rooms only open once the volunteer has given the task") --
    // 'rewarded' stays listed too so backtracking after the reward never re-locks the stairs.
    doorLocks: [{ match: 'Main Block Stairs G (up)', stages: ['hunting', 'rewarded'] }],
    npcs: [{
      id: 'lug-volunteer',
      name: 'LUG Volunteer',
      character: 'volunteer',
      x: 57,
      y: 62, // the nook behind the foyer's decorative staircase (docs/INTERIORS_PLAN.md "LUG Stall")
      facing: 'down',
      dialog: STORY.volunteer,
    }],
  },
  'main-block-1': {
    name: 'Main Block · 1st Floor',
    tiled: 'main-block-1',
    indoors: true,
    doorLocks: [{ match: 'Main Block Stairs 1 (up)', stages: ['hunting', 'rewarded'] }],
    keyStations: [
      // Coordinates sit exactly on a real furniture tile in each room (checked against the
      // generated map, docs/INTERIORS_PLAN.md): ICVL's is a lab bench, Room 195's is the teacher's desk.
      { id: 'icvl', name: STORY.keyStations.icvl.name, item: STORY.keyStations.icvl.item, x: 50, y: 34, dialog: keyStationDialog('icvl') },
      { id: 'room195', name: STORY.keyStations.room195.name, item: STORY.keyStations.room195.item, x: 61, y: 34, dialog: keyStationDialog('room195') },
    ],
  },
  'main-block-2': {
    name: 'Main Block · 2nd Floor',
    tiled: 'main-block-2',
    indoors: true,
    // No key here (the Physics Lab moved to the 3rd floor, docs/INTERIORS_PLAN.md) -- this floor is
    // just a through-route to the 3rd, so it opens on the same condition as every other Main Block
    // stairwell rather than being sealed off (docs/STORY.md "the routes to the three key rooms").
    doorLocks: [{ match: 'Main Block Stairs 2 (up)', stages: ['hunting', 'rewarded'] }],
  },
  'main-block-3': {
    name: 'Main Block · 3rd Floor',
    tiled: 'main-block-3',
    indoors: true,
    keyStations: [
      { id: 'physicsLab', name: STORY.keyStations.physicsLab.name, item: STORY.keyStations.physicsLab.item, x: 114, y: 34, dialog: keyStationDialog('physicsLab') },
    ],
  },
  'library-block-g': { name: 'Library Block · Ground Floor', tiled: 'library-block-g', indoors: true },
  'library-block-1': { name: 'Library Block · 1st Floor', tiled: 'library-block-1', indoors: true },
  'mechanical-block-g': { name: 'Mechanical Block · Ground Floor', tiled: 'mechanical-block-g', indoors: true },
  'mechanical-block-1': { name: 'Mechanical Block · 1st Floor', tiled: 'mechanical-block-1', indoors: true },

  // Test maps (open with ?map=meadow)
  meadow: {
    name: 'Meadow',
    tutorial: true,
    legend: {
      '.': 'grass', ',': 'grass2', '*': 'flowers', '"': 'tallgrass',
      '=': 'path', '~': 'water', T: 'tree', o: 'rock',
    },
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'T.,....,.,.....,==.....................T',
      'T.TTT.,,...,..,.==....,.,,....~~~~~.,.,T',
      'T.TTT......T,.*.==,."""""""..~~~~~~~...T',
      'T..T,......,.,..==.,"""""""..~~~~~~~..,T',
      'T....,....,,,,,,==*,"""""""..~~~~~~~.,.T',
      'T,.....,..,,.,..==.."""""""..~~~~~~~...T',
      'T,......TT.,....==.."""""""...~~~~~.,,.T',
      'T.,.o.,,TT...,..==.....,,..........,...T',
      'T,......TT.,.,,.==,.....,,..,...,,,....T',
      'T........,,.....==,,..T.,,,..,*...TTTT.T',
      'T,....o.........==.......,......,.TTTT.T',
      'T.........*.....==.*.....,*,.......,,,.T',
      'T...,...,..=....==.,.......,,........,.T',
      'T..==================================..T',
      'T.,==================================,,T',
      'T......,,..,.....,....,.,...==...,,,*..T',
      'T..,.*..,..,.o.........,,o,.==........,T',
      'T..................,......,.==,..,.....T',
      'T...,.,~~~~~~~~.,...,,.,..,.==,.""""",,T',
      'T.,.,,~~~~~~~~~~.,,..,..,...==,."""""..T',
      'T.,...~~~~~~~~~~..,.,.,,....==..""""",,T',
      'T.,,..~~~~~~~~~~....TTT,,...==,."""""..T',
      'T..,..~~~~~~~~~~....TTT..,..==..""""",.T',
      'T...,.~~~~~~~~~~..,.....,,..==.."""""..T',
      'T,....,~~~~~~~~.,..,,.....,.==,....,...T',
      'TTTTTT......,.,....o...*....==......,..T',
      'TTTTTT.,.,,,*...,.,......,..==.,...,.o.T',
      'TTTTTT....,......,........,...,.,......T',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    spawn: { x: 17, y: 12, facing: 'down' },
    structures: [{ type: 'house', x: 9, y: 9 }],
    // Step on a warp tile to go to another map. The house door is at (11, 12).
    warps: [{ x: 11, y: 12, to: 'house', spawn: { x: 9.5, y: 10, facing: 'up' } }],
    pickups: [
      { id: 'meadow-apple-1', item: 'apple', x: 20, y: 12 },
      { id: 'meadow-apple-2', item: 'apple', x: 6, y: 17 },
      { id: 'meadow-phone', item: 'phone', x: 24, y: 8 },
      { id: 'meadow-notebook', item: 'notebook', x: 34, y: 21 },
    ],
    // A second test-map NPC (alongside Tomas in the house), purely to exercise dialog choices
    // (roadmap M1) end to end: a plain intro line, then a Yes/No choice, each branch with its own
    // follow-up line and actions. Not story content (docs/STORY.md) -- an engine fixture like Tomas.
    npcs: [{
      id: 'guide',
      name: 'Guide',
      x: 14,
      y: 12,
      facing: 'down',
      dialog: [{
        id: 'ask-hint',
        lines: ['Want a hint about the meadow?'],
        choices: [
          {
            text: 'Yes, please!',
            lines: ['Check the tall grass to the east.'],
            actions: [{ setFlag: 'guideHintYes' }, { toast: 'Hint received!' }],
          },
          {
            text: 'No thanks.',
            lines: ['Suit yourself.'],
            actions: [{ setFlag: 'guideHintNo' }],
          },
        ],
      }],
    }, {
      // FB-0025/ADR 0013: fixtures proving the new recolored-pack NPC pipeline end to end (the
      // `character` field picks a texture -- see world.js createNpcs()), the same way Guide above is
      // an engine fixture rather than story content. Real campus placement is a follow-up task; for
      // now these three just need somewhere walkable to stand and something to say.
      id: 'lug-volunteer-demo',
      name: 'LUG Volunteer',
      character: 'volunteer',
      x: 6,
      y: 5,
      facing: 'down',
      dialog: [{ id: 'chat', lines: ["Looking for the LUG treasure hunt? It kicks off on campus."] }],
    }, {
      id: 'campus-student-a-demo',
      name: 'Student',
      character: 'student-a',
      x: 30,
      y: 9,
      facing: 'down',
      dialog: [{ id: 'chat', lines: ["Ugh, I still haven't finished my assignment."] }],
    }, {
      id: 'campus-student-b-demo',
      name: 'Student',
      character: 'student-b',
      x: 10,
      y: 27,
      facing: 'down',
      dialog: [{ id: 'chat', lines: ['Nice weather for a walk, isn\'t it?'] }],
    }],
  },

  house: {
    name: "Tomas's House",
    indoors: true, // no running indoors (FB-0017)
    legend: {
      '^': 'wallUpper', '|': 'wallLower', W: 'wallWindow', B: 'bookshelf', E: 'edge',
      '.': 'floor', r: 'rug', t: 'table', h: 'bedHead', f: 'bedFoot', p: 'plant',
      m: 'doormat', d: 'doorway',
    },
    rows: [
      'E^^^^^^^^^^^^^^^^^^E',
      'E||W||BB||||W|||B||E',
      'Eh.................E',
      'Ef...........p.....E',
      'E..................E',
      'E.....rrrrrr.......E',
      'E.....rrrrrr...t...E',
      'E.....rrrrrr.......E',
      'Ep.................E',
      'E..................E',
      'E........mm.......pE',
      'EEEEEEEEEddEEEEEEEEE',
    ],
    spawn: { x: 9.5, y: 10, facing: 'up' },
    warps: [
      { x: 9, y: 11, to: 'meadow', spawn: { x: 11, y: 13, facing: 'down' } },
      { x: 10, y: 11, to: 'meadow', spawn: { x: 11, y: 13, facing: 'down' } },
    ],
    pickups: [
      { id: 'house-keycard', item: 'keycard', x: 3, y: 5 },
      { id: 'house-idcard', item: 'idCard', x: 16, y: 2 },
      { id: 'house-laptop', item: 'laptop', x: 14, y: 6 },
      { id: 'house-coffee', item: 'coffee', x: 17, y: 9 },
    ],
    npcs: [{
      id: 'tomas',
      name: 'Tomas',
      x: 8,
      y: 4,
      facing: 'down',
      // Data-driven dialog (src/dialog.js, docs/ARCHITECTURE.md): the first entry whose `when`
      // matches GameState wins. Kept as the engine's test-map example (CLAUDE.md: the owner writes
      // the real story; the LUG volunteer's script arrives in M3).
      dialog: [
        {
          id: 'give-sword',
          when: { notFlag: 'tomasGaveSword' },
          lines: [
            'Oh! A visitor! Nobody has knocked on my door in a long time.',
            "I'm Tomas. I've looked after this meadow for sixty years.",
            'You look like an adventurer. Here, take my old sword.',
            'My back is too stiff to swing it these days. Look after it!',
          ],
          actions: [
            { give: 'sword' },
            { setFlag: 'tomasGaveSword' },
            { toast: 'You got the Old Sword!' },
          ],
        },
        // After the sword, Tomas cycles through 3 chats (`tomasChats` wraps 0 -> 1 -> 2 -> 0 -- the
        // same rotation the old hand-written talk() used), each entry advancing the counter itself.
        {
          id: 'chat-0',
          when: { flag: 'tomasChats', value: 0 },
          lines: ['I hear strange noises past the trees at night...', 'Keep that sword close.'],
          actions: [{ setFlag: { name: 'tomasChats', value: 1 } }],
        },
        {
          id: 'chat-1',
          when: { flag: 'tomasChats', value: 1 },
          lines: ["I've dropped a few things around the meadow over the years.", 'Try the tall grass. Things love to hide in there.'],
          actions: [{ setFlag: { name: 'tomasChats', value: 2 } }],
        },
        {
          id: 'chat-2',
          when: { flag: 'tomasChats', value: 2 },
          lines: ['The lake to the south is lovely at sunset.', 'Far too cold for swimming, mind you.'],
          actions: [{ setFlag: { name: 'tomasChats', value: 0 } }],
        },
      ],
    }],
  },
};
