// FB-0044: every character sheet the content references must exist as a generated PNG *and* be queued
// by BootScene's preload. `npc-ambient-a..f` were generated by tools/make-assets.js but never loaded
// (src/main.js only listed three sheets by hand), so some students drew as Phaser's black box with a
// green diagonal (`__MISSING`). The preload list is now derived from the content itself
// (src/maplogic.js characterSheets()); these tests pin that derivation to the content and the art.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { ROOT, loadGameData } = require('../helpers/game-data');

const { MAPS, AMBIENT, SCRIPTS, characterSheets, ambientSheetKey } = loadGameData();
const plainList = (list) => JSON.parse(JSON.stringify(list)); // sandbox arrays have another realm's prototype

// Texture keys the content references, collected independently of characterSheets() (a plain walk of
// the same three sources) so the registry can't silently drop one and still agree with itself.
function referencedKeys() {
  const keys = new Set();
  for (const def of Object.values(MAPS)) {
    for (const npc of def.npcs || []) keys.add(npc.character ? `npc-${npc.character}` : 'npc');
  }
  // FB-0057: an ambient student draws with her club's outfit sheet (src/campus-facts.js ambientSheetKey()).
  for (const list of Object.values(AMBIENT)) for (const entry of list) keys.add(ambientSheetKey(entry));
  const walk = (node) => {
    if (Array.isArray(node)) return node.forEach(walk);
    if (!node || typeof node !== 'object') return;
    if (node.spawnActor && node.spawnActor.kind !== 'image') keys.add(node.spawnActor.sprite);
    Object.values(node).forEach(walk);
  };
  walk(Object.values(SCRIPTS));
  return keys;
}

// The art the generator makes: every `write('<name>.png', ...)` call in tools/make-assets.js. Read from
// the source (not by running the generator, which needs the git-ignored assets/vendor/ packs and is
// already exercised end to end by tests/unit/assets.test.js), so this holds in any checkout.
function generatedAssetNames() {
  const source = fs.readFileSync(path.join(ROOT, 'tools', 'make-assets.js'), 'utf8');
  const names = new Set([...source.matchAll(/write\('([^']+\.png)'/g)].map((m) => m[1]));
  // FB-0057: the club-outfit variants are written by one loop over AMBIENT_BODIES x CLUB_OUTFITS (npc-<character>-<outfit>.png).
  const outfits = [...source.matchAll(/^  (sky|acm|lug|mtc): \{ shirt:/gm)].map((m) => m[1]);
  const bodies = [...source.matchAll(/'((?:ambient|student)-[a-f])': \['(?:Adam|Alex|Bob)'/g)].map((m) => m[1]);
  for (const body of bodies) for (const outfit of outfits) names.add(`npc-${body}-${outfit}.png`);
  return names;
}

test('FB-0044: the sheet registry covers every NPC, ambient student and script actor, and nothing else', () => {
  const keys = referencedKeys();
  // Sanity: the sources really contribute (a typo'd walk above would otherwise pass vacuously).
  for (const expected of ['npc', 'npc-volunteer', 'npc-student-a', 'npc-student-b', 'npc-mustafa',
    'npc-ambient-a', 'npc-ambient-b', 'npc-ambient-c', 'npc-ambient-d', 'npc-ambient-e', 'npc-ambient-f']) {
    assert.ok(keys.has(expected), `expected "${expected}" to be referenced by the content`);
  }
  assert.ok(!keys.has('bus'), 'the bus is a plain image (spawnActor kind "image"), not a character sheet');

  const sheets = characterSheets(MAPS, AMBIENT, SCRIPTS);
  assert.deepEqual(plainList(sheets.map((s) => s.key).sort()), [...keys].sort());
  assert.equal(new Set(sheets.map((s) => s.key)).size, sheets.length, 'no duplicate keys (Phaser would skip a repeated load)');
  for (const { key, file } of sheets) assert.equal(file, `assets/${key}.png`);
});

test('FB-0044: every referenced character key has a generated PNG, and is in the preload list', () => {
  const generated = generatedAssetNames();
  const preload = new Set(characterSheets(MAPS, AMBIENT, SCRIPTS).map((s) => s.key));
  for (const key of referencedKeys()) {
    assert.ok(generated.has(`${key}.png`), `tools/make-assets.js doesn't generate ${key}.png (referenced by the content)`);
    assert.ok(fs.existsSync(path.join(ROOT, 'assets', `${key}.png`)), `assets/${key}.png is missing on disk`);
    assert.ok(preload.has(key), `"${key}" is referenced by the content but not in BootScene's preload list`);
  }
});

test('FB-0044: BootScene loads its character sheets from the registry, not a hand-kept list', () => {
  const main = fs.readFileSync(path.join(ROOT, 'src', 'main.js'), 'utf8');
  assert.match(main, /characterSheets\(MAPS, AMBIENT, SCRIPTS\)/, 'src/main.js preload must iterate characterSheets()');
  // No hard-coded per-character loads left behind (the 'player' sheet is chosen by clothes colour, not a content reference).
  const hardCoded = [...main.matchAll(/load\.spritesheet\('([^']+)'/g)].map((m) => m[1]).filter((k) => k.startsWith('npc'));
  assert.deepEqual(hardCoded, [], `hand-kept NPC loads in src/main.js: ${hardCoded.join(', ')}`);
});

test('FB-0044: a new character referenced by any source reaches the preload list without touching main.js', () => {
  const sheets = characterSheets(
    { m: { npcs: [{ id: 'a' }, { id: 'b', character: 'zed' }] } },
    { m: [{ id: 'amb', character: 'ambient-z' }] },
    { s: [{ spawnActor: { id: 'x', sprite: 'npc-guest' } }, { spawnActor: { id: 'bus', sprite: 'bus', kind: 'image' } }] },
  );
  assert.deepEqual(plainList(sheets.map((s) => s.key)), ['npc', 'npc-ambient-z', 'npc-guest', 'npc-zed']);
});
